name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run pyright
        run: pyright
  
build_and_push:
  runs-on: ubuntu-latest
  steps:
    - name: Login to Docker Hub
    - uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #Fix space and validate variables
    - name: Prepare image vars
      run: |
        DU=$(printf %s '${{ vars.DOCKER_USERNAME }}' | tr -d '[:space:]')
        if [ -z "$DU" ]; then
          echo "ERROR: Actions Variable DOCKER_USERNAME is not set." >&2
          exit 1
        fi
        echo "DOCKER_USERNAME=$DU" >> $GITHUB_ENV

        # force repo name to lowercase for a valid reference
        echo "IMAGE_NAME=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

